[svn-upgrade] Integrating new upstream version, rt61 (1.1.0.dfsg.2+cvs20071207)

diff --git a/Module/Makefile b/Module/Makefile
--- a/Module/Makefile
+++ b/Module/Makefile
@@ -95,7 +95,7 @@ ifeq ($(PATCHLEVEL), 4)
  MODULE_CONF := /etc/modules.conf
 else
  MODULE_OBJECT := $(MODULE_NAME).ko
- MODULE_CONF := /etc/modprobe.conf
+ MODULE_CONF := /etc/modprobe.d/ralink
 endif
 
 all: module
@@ -112,7 +112,7 @@ MODULE_CHECK :=	if ! [ -f $(MODULE_OBJECT) ]; then \
 			exit 1; \
 		fi; \
 		if [ `du -b $(MODULE_OBJECT) | sed -e 's/\t.*//g'` -gt 1000000 ]; then \
-			echo "!!! WARNING: Module file much too big (>1MB),"; \
+			echo "!!! WARNING: Module file much too big (>1MB)"; \
 			echo "!!! Check your kernel settings or use 'strip'"; \
 		fi; \
 		echo "*** Module $(MODULE_OBJECT) built successfully"
@@ -136,7 +136,7 @@ clean:
 
 modules_install:
 	@if ! [ -f $(MODULE_OBJECT) ]; then \
-		echo "!!! $(MODULE_OBJECT) does not exit: run 'make'"; \
+		echo "!!! $(MODULE_OBJECT) does not exist: run 'make'"; \
 		exit 1; \
 	fi
 	@echo "*** Install module in $(MODULE_ROOT) ..."
@@ -150,8 +150,20 @@ endif
 
 install: modules_install
 	@echo "*** Update $(MODULE_CONF) alias for $(IF_NAME)"; \
-	if ! grep -q '$(IF_NAME)' $(MODULE_CONF) ; then \
-		echo "alias $(IF_NAME) $(MODULE_NAME)" >> $(MODULE_CONF) ; \
+	if [ -d `dirname $(MODULE_CONF)` ]; then \
+		if [ -s $(MODULE_CONF) ]; then \
+			if ! grep -q '$(IF_NAME)' $(MODULE_CONF) ; then \
+				echo "alias $(IF_NAME) $(MODULE_NAME)" >> $(MODULE_CONF) ; \
+			fi; \
+		else \
+			echo "alias $(IF_NAME) $(MODULE_NAME)" >> $(MODULE_CONF) ; \
+		fi; \
+		if grep -q '$(OLD_IF_NAME)' $(MODULE_CONF) ; then \
+			echo "!!! -> $(OLD_IF_NAME) interface name is deprecated:" \
+						"remove old $(MODULE_CONF) alias"; \
+		fi; \
+	else \
+		echo "*** Config dir `dirname $(MODULE_CONF)` not found" >&2; \
 	fi
 	@echo "*** Install firmware in $(FIRM_DIR) ..."; \
 	if ! [ -d $(FIRM_DIR) ]; then \
@@ -169,12 +181,8 @@ install: modules_install
 					"use iwconfig/iwpriv instead"; \
 		fi; \
 		if [ -f $(CONFIG_DIR)/$(FIRMWARES) ]; then \
-			echo "!!! -> $(FIRMWARES) firmwares have moved to $(FIRM_DIR)"; \
+			echo "!!! -> $(FIRMWARES) firmware has moved to $(FIRM_DIR)"; \
 		fi; \
-	fi; \
-	if grep -q '$(OLD_IF_NAME)' $(MODULE_CONF) ; then \
-		echo "!!! -> $(OLD_IF_NAME) interface name is deprecated:" \
-					"remove old $(MODULE_CONF) alias"; \
 	fi
 
 ifeq ($(PATCHLEVEL), 4)
